all:
  vars:
    ansible_user: chomsmaster
    ansible_python_interpreter: /usr/bin/python3

  children:
    kubernetes:
      children:
        control_plane:
          hosts:
            choms-node-01:
              ansible_host: 192.168.1.138

        workers:
          hosts:
            choms-node-02:
              ansible_host: 192.168.1.172

            choms-node-03:
              ansible_host: 192.168.1.134

    storage:
      hosts:
        choms-nas:
          ansible_host: 192.168.1.167

    development:
      hosts:
        node-dev-01:
          ansible_connection: local
