apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scrutiny-collector
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: scrutiny-collector
  template:
    metadata:
      labels:
        app: scrutiny-collector
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        scrutiny-collector: "enabled"

      tolerations:
        - {key: node-role.kubernetes.io/control-plane, operator: Exists, effect: NoSchedule}

      containers:
        - name: collector
          image: ghcr.io/analogj/scrutiny@sha256:3274a8c1e4b48bcc42089f9431f89604d4b3a661aeeaa2029c59c352d41762c2
          imagePullPolicy: IfNotPresent

          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi

          securityContext:
            privileged: true

          env:
            - name: COLLECTOR_API_ENDPOINT
              value: http://scrutiny.monitoring.svc.cluster.local:8080

            - name: COLLECTOR_HOST_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

            - name: COLLECTOR_RUN_STARTUP
              value: "true"

            - name: COLLECTOR_CRON_SCHEDULE
              value: "0 */6 * * *"

          volumeMounts:
            - name: udev
              mountPath: /run/udev
              readOnly: true

            - name: dev
              mountPath: /dev

      volumes:
        - name: udev
          hostPath:
            path: /run/udev
            type: Directory

        - name: dev
          hostPath:
            path: /dev
            type: Directory
