http:
  middlewares:
    secure-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: false

  routers:
    traefik:
      rule: "Host(`traefik.chomsmaster.com`)"
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - authelia@docker
      tls:
        certResolver: letsencrypt

    jellyfin:
      rule: "Host(`jellyfin.chomsmaster.com`)"
      entryPoints:
        - websecure
      service: jellyfin
      tls:
        certResolver: letsencrypt

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8096"
