http:
  middlewares:
    secure-headers:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: false

  routers:
    traefik:
      rule: "Host(`traefik.chomsmaster.com`)"
      entryPoints:
        - websecure
      service: api@internal
      middlewares:
        - authelia@docker
      tls:
        certResolver: letsencrypt

    jellyfin:
      rule: "Host(`jellyfin.chomsmaster.com`)"
      entryPoints:
        - websecure
      service: jellyfin
      tls:
        certResolver: letsencrypt

    torrent:
      rule: "Host(`torrent.chomsmaster.com`)"
      entryPoints:
        - websecure
      service: torrent
      tls:
        certResolver: letsencrypt

    fbrowser:
      rule: "Host(`fbrowser.chomsmaster.com`)"
      entryPoints:
        - websecure
      service: fbrowser
      tls:
        certResolver: letsencrypt

  services:
    jellyfin:
      loadBalancer:
        servers:
          - url: "http://192.168.1.172:8096"
    torrent:
      loadBalancer:
        servers:
          - url: "http://192.168.1.167:8080"
    fbrowser:
      loadBalancer:
        servers:
          - url: "http://192.168.1.167:8088"
