services:
  nginx:
    image: nginx:stable-alpine
    container_name: choms-nginx
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home.rule=Host(`home.chomsmaster.com`)"
      - "traefik.http.routers.home.entrypoints=websecure"
      - "traefik.http.routers.home.tls.certresolver=letsencrypt"
      - "traefik.http.routers.home.middlewares=authelia@docker"
      - "traefik.http.routers.home.service=home"
      - "traefik.http.services.home.loadbalancer.server.port=80"
      - "traefik.http.routers.www.rule=Host(`www.chomsmaster.com`) || Host(`chomsmaster.com`)"
      - "traefik.http.routers.www.entrypoints=websecure"
      - "traefik.http.routers.www.tls.certresolver=letsencrypt"
      - "traefik.http.routers.www.service=www"
      - "traefik.http.services.www.loadbalancer.server.port=80"
    volumes:
      - /data/websites/choms-test:/usr/share/nginx/html:ro
      - /data/websites/choms-test/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /data/websites/chomsmaster-public:/usr/share/nginx/public:ro

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8081:80/tcp"
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - /data/pihole/etc-pihole:/etc/pihole
      - /data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

  traefik:
    image: traefik:latest
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: choms-traefik
    restart: unless-stopped
    command:
      - --api.dashboard=true
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --providers.file.filename=/etc/traefik/dynamic.yml
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.letsencrypt.acme.email=oscar_salcedo@hotmail.com
      - --certificatesresolvers.letsencrypt.acme.storage=/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/config/dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./traefik/acme.json:/acme.json
      - ./traefik/logs:/logs
